openapi: 3.0.0
servers: 
  - url: https://qxnyqbkn3m.execute-api.us-east-2.amazonaws.com/
    description: aws api server
info:
  title: Bitracker
  description: .
  version: 0.0.1

paths:
  # CRYPTO NAME
  # crypto_name+ instructs AWS API Gateway to handle path variables.
  /v1/crypto/{crypto_name+}:
    get:
      tags: []
      operationId: crypto_price
      summary: Get crypto crypto_name price
      description: '.'
      parameters:
        - $ref: '#/components/parameters/crypto_name'
        - $ref: '#/components/parameters/currency'
        - $ref: '#/components/parameters/cmc_api_key'
      responses:
        '200':
          description: Price returned
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/price'
          
        '404': { $ref: '#/components/responses/NotFound' }

  /v1/history/{crypto_name+}:
    get:
      tags: []
      operationId: historical_crypto_prices
      summary: Get historical crypto prices.
      description: Get the crypto prices for the crypto provided as a path 
                   parameter starting from start_time to end_time.
      parameters:
        - $ref: '#/components/parameters/crypto_name'
        - $ref: '#/components/parameters/start_time'
        - $ref: '#/components/parameters/end_time'
        - $ref: '#/components/parameters/max_results'
      
      responses:
        '200':
          description:
          content:
            application/json:
              schema:
                $ref: ""
        
        '404': { $ref: '#/components/responses/NotFound' }


components:
  parameters:
    crypto_name:
      name: crypto_name
      in: path
      required: true
      description: Crypto name
      schema:
        $ref: '#/components/schemas/crypto_name'
        
    cmc_api_key:
      name: cmc_api_key
      in: header
      required: true
      description: Coinmarketcap API key.
      schema:
        $ref: '#/components/schemas/cmc_api_key'
        
    currency:
      name: currency
      in: query
      required: false
      description: Currency the price will be calculated over.
      schema:
        $ref: '#/components/schemas/currency'

    start_time:
      name: start_time
      in: query
      required: true
      description: Time to start the search from.
      schema:
        $ref: '#/components/schemas/time'
        
    end_time:
      name: start_time
      in: query
      required: true
      description: Time to end the search at.
      schema:
        $ref: '#/components/schemas/time'

    max_results:
      name: max_results
      in: query
      required: false
      default: 5
      description: Max results returned by the API call.
      schema: 
        $ref: '#/components/schemas/max_results'


  schemas:
    crypto_name:
      title: crypto_name
      type: string
      example: bitcoin
      
    price:
      title: price
      type: integer
      example: 44444.4
    
    cmc_api_key:
      title: cmc_api_key
      type: string
      example: abcdefghijkl
      
    currency:
      title: currency
      type: string
      example: EUR

    time:
      title: time
      type: time

    max_results:
      title: max_results
      type: integer
      example: 10

  responses:
    NotFound:
      description: The resource requested was not found
    Unauthorized:
      description: The access token is missing or it's expired
    BadRequest:
      description: The request was not compliant with the documentation (eg. missing fields, etc)
    InternalServerError:
      description: The server encountered an internal error. Further info in server logs

  
