name: Publish Bitracker

on:
  push: 
    branches: ['devel']
    paths-ignore:
      - "README.md"
      
jobs:
  # deploy-lambda deploys the python backend code on AWS as a lambda
  # from a zip package created with the necessary dependencies.
  deploy-inspector-lambda:
    runs-on: ubuntu-latest
    env:
      FUNC_NAME: inspector.py
      ZIP_FILE: bitracker-inspector.zip
      LAMBDA_NAME: bitracker_inspector

    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Install pip
      run: |
        python -m pip install --upgrade pip

    - name: Create zip package
      run: |
        pip install --target ./pack requests boto3 
        cd pack 
        zip -r ../$ZIP_FILE .
        cd ..
        mv backend/$FUNC_NAME .
        zip -g $ZIP_FILE $FUNC_NAME
      
    - name: Publish lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: bitracker_inspector
        zip_file: './bitracker-inspector.zip'   

  deploy-historical-price-lambda:
    runs-on: ubuntu-latest
    env:
      FUNC_NAME: get_historical_price.py
      ZIP_FILE: bitracker-get-historical-price.zip
      LAMBDA_NAME: bitracker_get_historical_price
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Install pip
      run: |
        python -m pip install --upgrade pip

    - name: Create zip package
      run: |
        pip install --target ./pack boto3 
        cd pack 
        zip -r ../$ZIP_FILE .
        cd ..
        mv backend/$FUNC_NAME .
        zip -g $ZIP_FILE $FUNC_NAME
      
    - name: Publish lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: bitracker_get_historical_price
        zip_file: './bitracker-get-historical-price.zip'   