# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push: 
    branches: ['git_action']
    paths-ignore:
      - "README.md"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout 
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
    
    - name: is_publish_type
      if: ${{ contains(github.event.head_commit.message, 'Telegram') || contains(github.event.head_commit.message, 'Cli') }}
      run: |
        if [[ "${{github.event.head_commit.message}}" == "Telegram"* ]]; 
        then
          echo "PUBLISH_TYPE=Telegram" >> $GITHUB_ENV;
        fi
        if [[ "${{github.event.head_commit.message}}" == "Cli"* ]]; then
          echo " PUBLISH_TYPE=Cli" >> $GITHUB_ENV;
        fi
    
    - name: is_publish_type
      run: |
        echo $PUBLISH_TYPE

